### ISSUE TITLE
Unexpected reserved word - import

### ISSUE THREAD

**Issue by eldinoyev** [syntaxhighlighter/brush-base#1]
Trying to use brush.getHtml in Node, 'brush-base' throws an error because of lack of support for es6 'import'. 

![image](https://cloud.githubusercontent.com/assets/11944012/13686032/aa187004-e6e1-11e5-98f5-c7f28abcd1c1.png)

![image](https://cloud.githubusercontent.com/assets/11944012/13685982/6b08751c-e6e1-11e5-9439-04f553ed26b6.png)

**Comment by alexgorbatchev** [comment]
This is meant to be run with [Babel](http://babeljs.io/), add this before your `require`:

``` js
require("babel-register");
```

**Comment by alexgorbatchev** [comment]
Curious, what are you trying to do?

**Comment by eldinoyev** [comment]
Ah okay, I'll give that a shot and let you know how it works. I'm looking for a way to syntax-highlight Javascript and print its highlighted form into a console. Probably going to have to write a new renderer that returns JSON or something.

**Comment by alexgorbatchev** [comment]
Have a look at https://github.com/syntaxhighlighter/syntaxhighlighter-html-renderer/blob/master/index.js and specifically at `getHtml` function, which is a good place to start. You can strip that down and just use ASCII codes to do console highlighting. Please post an update here, I'd love to see and maybe help out where possible.

**Comment by eldinoyev** [comment]
Awesome! Thanks for the push in the right direction. I'll see what I can do and update you here.

**Comment by eldinoyev** [comment]
Hey man, I ended up making a little helper function with Cheerio to process the html string that brush.getHtml() produces. Figured this would be easier than tinkering with your dependency. It's here if you're interested: https://github.com/eldino/terminal-hackertyper/blob/master/src/syntaxHighlightJsonWrap.js
